@startuml
participant Client
    participant Server
    
    == Connection Establishment ==
    Client->>Server: HELLO
    Server-->>Client: PROJL [list]/ERROR
    
    == Project Operations ==
    Client->>Server: PROJS [name]
    
    Server-->>Client: PROJD [project_data]/ERROR
    
    == Project Modification ==
    Client->>Server: ADDPR [project_info]
    Server-->>Client: OKAYY/ERROR
    
    Client->>Server: DELPR [name]
    Server-->>Client: OKAYY/ERROR
    
    == Task Operations ==
    Client->>Server: ADDTS [task_info]
    Server-->>Client: OKAYY/ERROR
    
    Client->>Server: DELTS [name]
    Server-->>Client: OKAYY/ERROR

    == Task getters / modifiers ==
    Client->>Server: GETTS [name]
    Server-->>Client: TASKD [task_data]

    Client->>Server: MODTS [name] [task_data]
    Server-->>Client: OKAYY/ERROR

	== Close connection ==
	Client->>Server: CLOSE

@enduml
